### ISSUE TITLE
Standings_data division parameter should accept divisionId instead of only abbreviation

### ISSUE THREAD

**Issue by justintran12** [toddrob99/MLB-StatsAPI#115] opened 2023-05-22 22:55 UTC
Here is the documentation for the function:
statsapi.standings_data(leagueId="103,104", division="all", include_wildcard=True, season=None, standingsTypes=None, date=None).
Doing statsapi.standings_data(division = "200") or statsapi.standings_data("103", "200") returns empty dict.

I found I can just do this statsapi.standings_data(leagueId = "103")[200]) to get the division standings, so it's not a big deal, but just wanted to document the issue.

**Comment by SigireddyBalasai** [comment] 2023-07-06 14:44
i want to work on this

**Comment by jimcreel** [comment] 2023-07-20 16:24
I submitted a pull request for this enhancement if the issue is still available.

**Comment by toddrob99** [comment] 2023-07-29 18:40
released in v1.6.2

**Closed by toddrob99** 2023-07-29 18:40 UTC
Labels: enhancement
